name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP to IONOS
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: access-5020452873.webspace-host.com
          port: 22
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          localDir: ./
          remoteDir: /htdocs/
